FROM mcr.microsoft.com/devcontainers/rust:latest
# See https://mcr.microsoft.com/en-us/product/devcontainers/rust/about
# See https://hub.docker.com/_/microsoft-devcontainers-rust

CMD [ "/bin/bash" ]
